#!/bin/bash
# =============================================================================
# Way Back Home: Environment Variables
# =============================================================================
# Generated by setup_env.sh on Tue Mar  3 03:04:56 PM UTC 2026
# Source this file before running agents or deploying services.
# =============================================================================
#

# Add $HOME/.local/bin to PATH if running in Cloud Shell
if [ -n "$CLOUD_SHELL" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Check if gcloud is authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q "@"; then
    echo "Error: No active gcloud account found."
    echo "Please run 'gcloud auth login' and try again."
fi

# Get current project
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
if [ "$PROJECT_ID" == "(unset)" ] || [ -z "$PROJECT_ID" ]; then
    echo "Warning: No gcloud project is currently set."
    echo "Run 'gcloud config set project [PROJECT_ID]' to configure it."
fi

if [ -z "$CLOUD_SHELL" ]; then
    if ! gcloud auth application-default print-access-token > /dev/null 2>&1; then
        echo "ADC expired or not found. Initializing login..."
        gcloud auth application-default login
    else
        echo "ADC is valid."
    fi
fi

# Google Cloud Configuration
#export GOOGLE_CLOUD_PROJECT="comglitn"
#export PROJECT_ID="comglitn"
export REGION="us-central1"
export GOOGLE_CLOUD_LOCATION="us-central1"

cat <<EOF > .env
GOOGLE_GENAI_USE_VERTEXAI=1
GOOGLE_CLOUD_PROJECT=$PROJECT_ID
GOOGLE_CLOUD_LOCATION=us-central1
EOF

source .env

echo "Current Environment"
cat .env

echo "Cloud Login"
gcloud auth list

# ADK Configuration - Required for adk web and agent execution
export GOOGLE_GENAI_USE_VERTEXAI=true

# Participant Configuration (from config.json)
# This is used by the agent's before_agent_callback to fetch participant data
export PARTICIPANT_ID="cc87d753"

# Backend API URL (for agent tools to confirm location, fetch participant data)
export BACKEND_URL="https://api.waybackhome.dev"

# Service Account for Cloud Run deployments
export SERVICE_ACCOUNT="way-back-home-sa@comglitn.iam.gserviceaccount.com"
export REPO_NAME="way-back-home"

# OneMCP BigQuery URL
export BIGQUERY_MCP_URL="https://bigquery.googleapis.com/mcp"

# These will be set after deploying services:
# export MCP_SERVER_URL="https://location-analyzer-xxx.a.run.app"
# export LEVEL1_AGENT_URL="https://mission-analysis-ai-xxx.a.run.app"

echo "Environment loaded for project: $PROJECT_ID (Vertex AI mode)"
if [ -n "$PARTICIPANT_ID" ]; then
    echo "Participant ID: $PARTICIPANT_ID"
fi
export MCP_SERVER_URL="https://location-analyzer-fgasxpwzoq-uc.a.run.app"
export LEVEL1_AGENT_URL="https://mission-analysis-ai-fgasxpwzoq-uc.a.run.app"

export SERVICE_NAME=biometric-scout
export IMAGE_PATH=gcr.io/${PROJECT_ID}/${SERVICE_NAME}
